print("\n")
print("===============================================")
print("   Welcome to Python Multi Image Downloader")
print("==============================================")

print("This is a problem solving project. And, It was developed to complete a task downloading 84,000 images and rename it with ImageID. Now this project can download 10000+ images in one go depending on your resources. ")
print("Basic functionality are: \n")
print(" 1. Can read txt file and search image for the given word")
print(" 2. If the image link is secure it will download the image,")
print(" 3. Downloaded Image will be renamed automatically before saving.")
print(" 4. Will deleted the word from txt file. So, that you can keep track of your work.")
print("\n\n")
print(input("   # Press ENTER to Continue..."))
print("Hello")
#import start_download